services:

  php_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php81_composer_app
    volumes:
      - .:/var/www
    networks:
      - mynetwork

  webserver:
    image: arm64v8/nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Monte le fichier de configuration Nginx personnalisé

    networks:
      - mynetwork

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork
  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "81:80"
    depends_on:
      - db
    networks:
      - mynetwork
networks:
  mynetwork:

volumes:
  dbdata:
